theme: jekyll-theme-slate

lang: zh-CN
title: 90ITer | 九零科技人 - 互联创造未来
description: 互联创造未来
show_downloads: false
safe: true
url: https://www.90iter.com
enforce_ssl: www.90iter.com
timezone: Asia/Shanghai
author: ZNing
